max_width = 100
use_field_init_shorthand = true
use_small_heuristics = "Max"

unstable_features = true
comment_width = 100
imports_granularity = "Item"
group_imports = "StdExternalCrate"
combine_control_expr = false
fn_single_line = true
where_single_line = true
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
format_generated_files = false
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
hex_literal_case = "Lower"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
use_try_shorthand = true
wrap_comments = true